2024/10/01 01:41:16 serving http on http://127.0.0.1:56741
2024/10/01 01:41:16 serving rpc on tcp://[::]:45263
2024/10/01 01:41:16 booting test machines...
2024/10/01 01:41:16 wait for the connection from test machine...
2024/10/01 01:41:27 XXX Fuzzer command: 
/syz-fuzzer -executor=/syz-executor -name=vm-1 -arch=amd64 -manager=localhost:45263 -sandbox=none -cover=true -debug=false  -optional=slowdown=1:sandbox_arg=0:pprof_port=6060
2024/10/01 01:41:35 machine check:
failed to read the following files in the VM:
/dev/raw-gadget                             : open /dev/raw-gadget: no such file or directory

BinFmtMisc              : enabled
Comparisons             : call 0 failed with errno 38
Coverage                : enabled
DelayKcovMmap           : enabled
DevlinkPCI              : PCI device 0000:00:10.0 is not available.  (errno 2: No such file or directory).
ExtraCoverage           : enabled
Fault                   : CONFIG_FAULT_INJECTION is not enabled.  (errno 2: No such file or directory).
KCSAN                   : write(/sys/kernel/debug/kcsan, on) failed.  (errno 2: No such file or directory).
LRWPANEmulation         : netlink: failed to get family id for nl802154: No such file or directory.  netlink_query_family_id failed.  (errno 2: No such file or directory).
Leak                    : failed to write(kmemleak, "scan=off").  (errno 2: No such file or directory).
NetDevices              : enabled
NetInjection            : tun: can't open /dev/net/tun.  (errno 2: No such file or directory).
NicVF                   : PCI device 0000:00:11.0 is not available.  (errno 2: No such file or directory).
SandboxAndroid          : enabled
SandboxNamespace        : enabled
SandboxSetuid           : enabled
Swap                    : enabled
USBEmulation            : failed to chmod /dev/raw-gadget.  (errno 2: No such file or directory).
VhciInjection           : socket(AF_BLUETOOTH, SOCK_RAW, BTPROTO_HCI) failed.  (errno 97: Address family not supported by protocol).
WifiEmulation           : netlink_query_family_id failed.  (errno 2: No such file or directory).
syscalls                : 2192/4499

2024/10/01 01:41:43 corpus                  : 29 (0 broken, 29 seeds)
2024/10/01 01:41:46 candidates=0 corpus=25 coverage=14007 exec total=759 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:41:56 candidates=0 corpus=31 coverage=14066 exec total=1179 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:41:57 update choice table with LLM
2024/10/01 01:41:57 UpdateChoiceTable using LLM comm content
2024/10/01 01:41:57 Build Choice Table with LLM
2024/10/01 01:42:06 candidates=0 corpus=45 coverage=14408 exec total=1614 (32/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:42:16 candidates=0 corpus=51 coverage=14460 exec total=1830 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:42:26 candidates=0 corpus=58 coverage=14574 exec total=2050 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:42:36 candidates=0 corpus=63 coverage=14648 exec total=2352 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:42:46 candidates=0 corpus=65 coverage=14704 exec total=2518 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:42:50 update choice table with LLM
2024/10/01 01:42:50 UpdateChoiceTable using LLM comm content
2024/10/01 01:42:50 Build Choice Table with LLM
2024/10/01 01:42:56 candidates=0 corpus=69 coverage=14706 exec total=2751 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:43:06 candidates=0 corpus=75 coverage=14725 exec total=2920 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:43:16 candidates=0 corpus=77 coverage=14727 exec total=2986 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:43:17 Hit times: 0
2024/10/01 01:43:26 candidates=0 corpus=112 coverage=15128 exec total=3872 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:43:36 candidates=0 corpus=159 coverage=16173 exec total=4969 (35/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:43:46 candidates=0 corpus=185 coverage=16413 exec total=6047 (40/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:43:56 candidates=0 corpus=202 coverage=16609 exec total=6447 (40/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:44:06 candidates=0 corpus=210 coverage=16635 exec total=6594 (38/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:44:16 candidates=0 corpus=211 coverage=16643 exec total=6647 (36/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:44:26 candidates=0 corpus=213 coverage=16647 exec total=6728 (35/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:44:36 candidates=0 corpus=220 coverage=17454 exec total=6900 (34/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:44:46 candidates=0 corpus=231 coverage=17749 exec total=7447 (35/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:44:56 Hit times: 0
2024/10/01 01:44:56 candidates=0 corpus=233 coverage=17760 exec total=7551 (34/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:45:06 candidates=0 corpus=278 coverage=18243 exec total=8631 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:45:16 candidates=0 corpus=312 coverage=18825 exec total=9520 (39/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:45:26 candidates=0 corpus=315 coverage=18833 exec total=9621 (38/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:45:36 candidates=0 corpus=326 coverage=19016 exec total=9855 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:45:46 candidates=0 corpus=325 coverage=19071 exec total=10121 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:45:56 candidates=0 corpus=335 coverage=19214 exec total=10507 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:46:06 candidates=0 corpus=372 coverage=19969 exec total=11575 (39/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:46:16 candidates=0 corpus=392 coverage=20294 exec total=12309 (41/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:46:17 update choice table with LLM
2024/10/01 01:46:17 UpdateChoiceTable using LLM comm content
2024/10/01 01:46:17 Build Choice Table with LLM
2024/10/01 01:46:26 candidates=0 corpus=418 coverage=20635 exec total=12970 (41/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:46:35 Hit times: 0
2024/10/01 01:46:36 candidates=0 corpus=432 coverage=20841 exec total=13224 (41/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:46:46 candidates=0 corpus=433 coverage=20999 exec total=13564 (41/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:46:56 candidates=0 corpus=433 coverage=20999 exec total=13612 (40/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:47:06 candidates=0 corpus=433 coverage=20999 exec total=13661 (39/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:47:16 candidates=0 corpus=438 coverage=21053 exec total=13719 (38/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:47:26 candidates=0 corpus=438 coverage=21053 exec total=13763 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:47:36 candidates=0 corpus=453 coverage=21337 exec total=13997 (36/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:47:46 candidates=0 corpus=508 coverage=22428 exec total=15241 (39/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:47:56 candidates=0 corpus=525 coverage=22600 exec total=15513 (38/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:48:06 candidates=0 corpus=528 coverage=22606 exec total=15571 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:48:16 candidates=0 corpus=530 coverage=22650 exec total=15635 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:48:26 candidates=0 corpus=547 coverage=22775 exec total=16009 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:48:36 candidates=0 corpus=573 coverage=23054 exec total=16691 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:48:46 candidates=0 corpus=576 coverage=23112 exec total=17155 (38/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:48:56 candidates=0 corpus=592 coverage=23286 exec total=17787 (38/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:49:06 candidates=0 corpus=624 coverage=23713 exec total=18479 (39/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:49:07 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:08 XXXXX REACH
2024/10/01 01:49:12 Hit times: 11
2024/10/01 01:49:12 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 01:49:16 candidates=0 corpus=624 coverage=23713 exec total=18479 (38/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:49:26 candidates=0 corpus=624 coverage=23713 exec total=18479 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:49:36 candidates=0 corpus=624 coverage=23713 exec total=18479 (36/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:49:46 candidates=0 corpus=616 coverage=23713 exec total=18479 (36/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:49:54 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 01:49:56 candidates=0 corpus=622 coverage=23850 exec total=18666 (35/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:50:06 candidates=0 corpus=646 coverage=24461 exec total=19206 (36/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:50:16 candidates=0 corpus=684 coverage=24821 exec total=20176 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:50:26 candidates=0 corpus=714 coverage=24971 exec total=20849 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:50:36 candidates=0 corpus=717 coverage=24973 exec total=20927 (37/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:50:46 candidates=0 corpus=712 coverage=24975 exec total=21018 (36/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:50:56 candidates=0 corpus=714 coverage=24978 exec total=21046 (36/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:51:06 candidates=0 corpus=716 coverage=24997 exec total=21121 (35/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:51:16 candidates=0 corpus=732 coverage=25083 exec total=21506 (35/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:51:26 candidates=0 corpus=735 coverage=25148 exec total=21615 (35/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:51:27 update choice table with LLM
2024/10/01 01:51:27 UpdateChoiceTable using LLM comm content
2024/10/01 01:51:27 Build Choice Table with LLM
2024/10/01 01:51:36 candidates=0 corpus=737 coverage=25168 exec total=21689 (34/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:51:46 candidates=0 corpus=732 coverage=25168 exec total=21736 (34/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:51:56 candidates=0 corpus=734 coverage=25623 exec total=21821 (34/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:52:06 candidates=0 corpus=736 coverage=25630 exec total=21925 (33/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:52:16 candidates=0 corpus=740 coverage=25686 exec total=22053 (33/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:52:26 candidates=0 corpus=743 coverage=25687 exec total=22191 (33/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:52:36 candidates=0 corpus=750 coverage=25726 exec total=22354 (32/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:52:46 candidates=0 corpus=753 coverage=25754 exec total=22447 (32/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:52:56 candidates=0 corpus=759 coverage=25813 exec total=22660 (32/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:53:06 candidates=0 corpus=774 coverage=25935 exec total=23244 (32/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:13 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:14 XXXXX REACH
2024/10/01 01:53:15 XXXXX REACH
2024/10/01 01:53:15 XXXXX REACH
2024/10/01 01:53:16 candidates=0 corpus=813 coverage=26487 exec total=24221 (33/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:53:18 Hit times: 24
2024/10/01 01:53:18 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 01:53:26 candidates=0 corpus=813 coverage=26487 exec total=24221 (33/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:53:36 candidates=0 corpus=813 coverage=26487 exec total=24221 (32/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:53:46 candidates=0 corpus=806 coverage=26487 exec total=24221 (32/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:53:56 candidates=0 corpus=806 coverage=26487 exec total=24221 (31/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:53:59 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 01:54:06 candidates=0 corpus=823 coverage=26603 exec total=24687 (32/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:54:16 candidates=0 corpus=826 coverage=26619 exec total=24774 (31/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:54:26 candidates=0 corpus=831 coverage=26625 exec total=24876 (31/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:54:36 candidates=0 corpus=854 coverage=26755 exec total=25340 (31/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:54:46 candidates=0 corpus=850 coverage=26757 exec total=25399 (31/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:54:56 candidates=0 corpus=856 coverage=26826 exec total=25513 (31/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:55:06 candidates=0 corpus=859 coverage=26828 exec total=25549 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:55:16 candidates=0 corpus=866 coverage=26866 exec total=25698 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:55:26 candidates=0 corpus=883 coverage=27494 exec total=26275 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:55:36 candidates=0 corpus=904 coverage=27647 exec total=26758 (31/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:55:46 candidates=0 corpus=909 coverage=27697 exec total=26999 (31/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:55:56 candidates=0 corpus=910 coverage=27707 exec total=27046 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:56:06 candidates=0 corpus=914 coverage=27707 exec total=27124 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:56:16 candidates=0 corpus=925 coverage=27788 exec total=27331 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:56:26 candidates=0 corpus=926 coverage=27789 exec total=27410 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:56:36 candidates=0 corpus=928 coverage=27792 exec total=27489 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:56:46 candidates=0 corpus=929 coverage=27794 exec total=27521 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:56:56 candidates=0 corpus=931 coverage=27843 exec total=27600 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:57:06 candidates=0 corpus=939 coverage=28144 exec total=27805 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:57:16 candidates=0 corpus=969 coverage=28432 exec total=28570 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:57:26 candidates=0 corpus=987 coverage=28779 exec total=29302 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:57:36 candidates=0 corpus=997 coverage=28854 exec total=29565 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:57:46 candidates=0 corpus=992 coverage=28865 exec total=29787 (30/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:57:56 candidates=0 corpus=993 coverage=28868 exec total=29930 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:58:00 XXXXX REACH
2024/10/01 01:58:00 XXXXX REACH
2024/10/01 01:58:02 XXXXX REACH
2024/10/01 01:58:02 XXXXX REACH
2024/10/01 01:58:03 XXXXX REACH
2024/10/01 01:58:03 XXXXX REACH
2024/10/01 01:58:03 XXXXX REACH
2024/10/01 01:58:03 Hit times: 7
2024/10/01 01:58:03 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 01:58:06 candidates=0 corpus=993 coverage=28868 exec total=29945 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:58:16 candidates=0 corpus=993 coverage=28868 exec total=29945 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:58:26 candidates=0 corpus=993 coverage=28868 exec total=29945 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:58:36 candidates=0 corpus=993 coverage=28868 exec total=29945 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:58:45 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 01:58:46 candidates=0 corpus=993 coverage=28868 exec total=29961 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:58:56 candidates=0 corpus=998 coverage=28909 exec total=30099 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:59:06 candidates=0 corpus=1001 coverage=28917 exec total=30218 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:59:16 candidates=0 corpus=1002 coverage=28917 exec total=30270 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:59:26 candidates=0 corpus=1006 coverage=28996 exec total=30341 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:59:36 candidates=0 corpus=1022 coverage=29177 exec total=30876 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:59:46 candidates=0 corpus=1012 coverage=29177 exec total=30930 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 01:59:56 candidates=0 corpus=1014 coverage=29191 exec total=30978 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:00:06 candidates=0 corpus=1034 coverage=29276 exec total=31371 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:00:16 candidates=0 corpus=1059 coverage=29480 exec total=31898 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:00:22 update choice table with LLM
2024/10/01 02:00:22 UpdateChoiceTable using LLM comm content
2024/10/01 02:00:22 Build Choice Table with LLM
2024/10/01 02:00:26 candidates=0 corpus=1081 coverage=29573 exec total=32437 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:00:36 candidates=0 corpus=1118 coverage=29834 exec total=33197 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:00:46 candidates=0 corpus=1138 coverage=31123 exec total=34147 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:00:56 candidates=0 corpus=1150 coverage=31203 exec total=34435 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:01:06 candidates=0 corpus=1154 coverage=31218 exec total=34517 (29/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:01:16 candidates=0 corpus=1160 coverage=31236 exec total=34694 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:01:26 candidates=0 corpus=1174 coverage=31310 exec total=35012 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:01:30 XXXXX REACH
2024/10/01 02:01:30 XXXXX REACH
2024/10/01 02:01:30 XXXXX REACH
2024/10/01 02:01:30 XXXXX REACH
2024/10/01 02:01:30 XXXXX REACH
2024/10/01 02:01:30 XXXXX REACH
2024/10/01 02:01:30 XXXXX REACH
2024/10/01 02:01:30 XXXXX REACH
2024/10/01 02:01:31 XXXXX REACH
2024/10/01 02:01:31 XXXXX REACH
2024/10/01 02:01:31 XXXXX REACH
2024/10/01 02:01:31 XXXXX REACH
2024/10/01 02:01:31 XXXXX REACH
2024/10/01 02:01:31 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:32 XXXXX REACH
2024/10/01 02:01:34 XXXXX REACH
2024/10/01 02:01:34 XXXXX REACH
2024/10/01 02:01:35 Hit times: 35
2024/10/01 02:01:35 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:01:36 candidates=0 corpus=1174 coverage=31310 exec total=35019 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:01:46 candidates=0 corpus=1158 coverage=31310 exec total=35019 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:01:56 candidates=0 corpus=1158 coverage=31310 exec total=35019 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:02:06 candidates=0 corpus=1158 coverage=31310 exec total=35019 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:02:15 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:02:16 candidates=0 corpus=1158 coverage=31310 exec total=35022 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:02:26 candidates=0 corpus=1163 coverage=31326 exec total=35160 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:02:36 candidates=0 corpus=1209 coverage=31600 exec total=36071 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:02:46 candidates=0 corpus=1205 coverage=31630 exec total=36166 (28/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:02:56 candidates=0 corpus=1215 coverage=31659 exec total=36313 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:03:06 candidates=0 corpus=1216 coverage=31663 exec total=36371 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:03:16 candidates=0 corpus=1216 coverage=31663 exec total=36395 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:03:26 candidates=0 corpus=1219 coverage=31665 exec total=36460 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:03:36 candidates=0 corpus=1226 coverage=31690 exec total=36723 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:03:46 candidates=0 corpus=1227 coverage=31690 exec total=36765 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:03:56 candidates=0 corpus=1230 coverage=31706 exec total=36801 (27/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:04:06 candidates=0 corpus=1230 coverage=31706 exec total=36839 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:04:16 candidates=0 corpus=1233 coverage=31721 exec total=36931 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:04:26 candidates=0 corpus=1234 coverage=31723 exec total=36981 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:04:36 candidates=0 corpus=1235 coverage=31724 exec total=37039 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:04:46 candidates=0 corpus=1236 coverage=31724 exec total=37077 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:04:56 candidates=0 corpus=1236 coverage=31724 exec total=37101 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:05:06 candidates=0 corpus=1238 coverage=31728 exec total=37125 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:05:16 candidates=0 corpus=1239 coverage=31743 exec total=37149 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:05:26 candidates=0 corpus=1239 coverage=31743 exec total=37180 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:05:36 candidates=0 corpus=1260 coverage=32026 exec total=37793 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:05:46 candidates=0 corpus=1259 coverage=32034 exec total=37952 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:05:56 candidates=0 corpus=1282 coverage=32306 exec total=38722 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:06:06 candidates=0 corpus=1305 coverage=32370 exec total=39198 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:06:16 candidates=0 corpus=1313 coverage=32418 exec total=39429 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:06:26 candidates=0 corpus=1315 coverage=32426 exec total=39487 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:06:36 candidates=0 corpus=1315 coverage=32426 exec total=39534 (26/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:06:46 candidates=0 corpus=1309 coverage=32434 exec total=39571 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:06:56 candidates=0 corpus=1311 coverage=32461 exec total=39618 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:07:06 candidates=0 corpus=1312 coverage=32470 exec total=39661 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:07:16 candidates=0 corpus=1312 coverage=32470 exec total=39709 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:07:26 candidates=0 corpus=1312 coverage=32470 exec total=39757 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:07:36 candidates=0 corpus=1315 coverage=32478 exec total=39800 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:07:46 candidates=0 corpus=1319 coverage=32492 exec total=39993 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:07:56 candidates=0 corpus=1326 coverage=32577 exec total=40356 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:08:06 candidates=0 corpus=1331 coverage=32590 exec total=40634 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:08:16 candidates=0 corpus=1337 coverage=32592 exec total=40862 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:08:26 candidates=0 corpus=1346 coverage=32629 exec total=41153 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:28 XXXXX REACH
2024/10/01 02:08:29 XXXXX REACH
2024/10/01 02:08:29 XXXXX REACH
2024/10/01 02:08:29 XXXXX REACH
2024/10/01 02:08:31 XXXXX REACH
2024/10/01 02:08:31 XXXXX REACH
2024/10/01 02:08:32 XXXXX REACH
2024/10/01 02:08:32 XXXXX REACH
2024/10/01 02:08:32 XXXXX REACH
2024/10/01 02:08:32 XXXXX REACH
2024/10/01 02:08:32 XXXXX REACH
2024/10/01 02:08:33 XXXXX REACH
2024/10/01 02:08:33 XXXXX REACH
2024/10/01 02:08:34 Hit times: 29
2024/10/01 02:08:34 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:08:36 candidates=0 corpus=1350 coverage=32653 exec total=41238 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:08:46 candidates=0 corpus=1345 coverage=32653 exec total=41238 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:08:56 candidates=0 corpus=1345 coverage=32653 exec total=41238 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:09:06 candidates=0 corpus=1345 coverage=32653 exec total=41238 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:09:16 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:09:16 candidates=0 corpus=1345 coverage=32653 exec total=41266 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:09:26 candidates=0 corpus=1364 coverage=32712 exec total=41635 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:09:36 candidates=0 corpus=1366 coverage=32718 exec total=41688 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:09:46 candidates=0 corpus=1366 coverage=32718 exec total=41715 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:09:56 candidates=0 corpus=1368 coverage=32724 exec total=41771 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:10:06 candidates=0 corpus=1387 coverage=32923 exec total=42186 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:10:16 candidates=0 corpus=1396 coverage=32975 exec total=42448 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:10:24 update choice table with LLM
2024/10/01 02:10:24 UpdateChoiceTable using LLM comm content
2024/10/01 02:10:24 Build Choice Table with LLM
2024/10/01 02:10:26 candidates=0 corpus=1410 coverage=33346 exec total=42827 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:10:36 candidates=0 corpus=1428 coverage=33599 exec total=43586 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:10:46 candidates=0 corpus=1424 coverage=33616 exec total=43804 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:10:56 candidates=0 corpus=1443 coverage=33725 exec total=44390 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:11:06 candidates=0 corpus=1453 coverage=33878 exec total=44566 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:11:16 candidates=0 corpus=1479 coverage=34051 exec total=45340 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:11:26 candidates=0 corpus=1489 coverage=34081 exec total=45527 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:11:36 candidates=0 corpus=1489 coverage=34081 exec total=45567 (25/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:11:46 candidates=0 corpus=1489 coverage=34157 exec total=45690 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:11:56 candidates=0 corpus=1489 coverage=34157 exec total=45718 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:12:06 candidates=0 corpus=1492 coverage=34188 exec total=45758 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:12:16 candidates=0 corpus=1509 coverage=34506 exec total=46103 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:12:26 candidates=0 corpus=1512 coverage=34520 exec total=46180 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:12:36 candidates=0 corpus=1515 coverage=34558 exec total=46207 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:12:46 candidates=0 corpus=1521 coverage=34600 exec total=46360 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:50 XXXXX REACH
2024/10/01 02:12:51 XXXXX REACH
2024/10/01 02:12:51 XXXXX REACH
2024/10/01 02:12:52 XXXXX REACH
2024/10/01 02:12:52 XXXXX REACH
2024/10/01 02:12:52 XXXXX REACH
2024/10/01 02:12:52 XXXXX REACH
2024/10/01 02:12:53 XXXXX REACH
2024/10/01 02:12:53 XXXXX REACH
2024/10/01 02:12:53 XXXXX REACH
2024/10/01 02:12:53 XXXXX REACH
2024/10/01 02:12:54 XXXXX REACH
2024/10/01 02:12:54 XXXXX REACH
2024/10/01 02:12:54 XXXXX REACH
2024/10/01 02:12:54 XXXXX REACH
2024/10/01 02:12:54 XXXXX REACH
2024/10/01 02:12:54 XXXXX REACH
2024/10/01 02:12:55 XXXXX REACH
2024/10/01 02:12:55 XXXXX REACH
2024/10/01 02:12:56 Hit times: 30
2024/10/01 02:12:56 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:12:56 candidates=0 corpus=1542 coverage=34859 exec total=46738 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:13:06 candidates=0 corpus=1542 coverage=34859 exec total=46738 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:13:16 candidates=0 corpus=1542 coverage=34859 exec total=46738 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:13:26 candidates=0 corpus=1542 coverage=34859 exec total=46738 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:13:36 candidates=0 corpus=1542 coverage=34859 exec total=46738 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:13:37 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:13:46 candidates=0 corpus=1553 coverage=34931 exec total=47203 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:13:56 candidates=0 corpus=1573 coverage=35109 exec total=47713 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:14:06 candidates=0 corpus=1583 coverage=35256 exec total=47945 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:14:16 candidates=0 corpus=1590 coverage=35274 exec total=48123 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:14:26 candidates=0 corpus=1592 coverage=35276 exec total=48171 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:14:36 candidates=0 corpus=1600 coverage=35306 exec total=48415 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:14:46 candidates=0 corpus=1588 coverage=35315 exec total=48485 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:14:56 candidates=0 corpus=1589 coverage=35323 exec total=48506 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:15:06 candidates=0 corpus=1589 coverage=35323 exec total=48529 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:15:16 candidates=0 corpus=1612 coverage=35707 exec total=49295 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:15:26 candidates=0 corpus=1632 coverage=35853 exec total=49713 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:15:36 candidates=0 corpus=1646 coverage=35938 exec total=50075 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:15:46 candidates=0 corpus=1650 coverage=36077 exec total=50370 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:15:56 candidates=0 corpus=1667 coverage=36239 exec total=50711 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:16:06 candidates=0 corpus=1681 coverage=36284 exec total=51070 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:16:16 candidates=0 corpus=1684 coverage=36308 exec total=51122 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:16:26 candidates=0 corpus=1685 coverage=36308 exec total=51158 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:16:36 candidates=0 corpus=1686 coverage=36308 exec total=51182 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:16:46 candidates=0 corpus=1688 coverage=36312 exec total=51226 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:16:56 candidates=0 corpus=1692 coverage=36361 exec total=51329 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:17:06 candidates=0 corpus=1697 coverage=36380 exec total=51405 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:17:16 candidates=0 corpus=1703 coverage=36387 exec total=51604 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:17:26 candidates=0 corpus=1714 coverage=36403 exec total=51992 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:17:36 candidates=0 corpus=1736 coverage=36595 exec total=52905 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:17:40 update choice table with LLM
2024/10/01 02:17:40 UpdateChoiceTable using LLM comm content
2024/10/01 02:17:40 Build Choice Table with LLM
2024/10/01 02:17:43 XXXXX REACH
2024/10/01 02:17:43 XXXXX REACH
2024/10/01 02:17:44 XXXXX REACH
2024/10/01 02:17:44 XXXXX REACH
2024/10/01 02:17:44 XXXXX REACH
2024/10/01 02:17:44 XXXXX REACH
2024/10/01 02:17:45 XXXXX REACH
2024/10/01 02:17:45 XXXXX REACH
2024/10/01 02:17:46 candidates=0 corpus=1723 coverage=36634 exec total=53038 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:17:46 XXXXX REACH
2024/10/01 02:17:46 XXXXX REACH
2024/10/01 02:17:46 XXXXX REACH
2024/10/01 02:17:46 XXXXX REACH
2024/10/01 02:17:47 XXXXX REACH
2024/10/01 02:17:47 XXXXX REACH
2024/10/01 02:17:48 XXXXX REACH
2024/10/01 02:17:48 XXXXX REACH
2024/10/01 02:17:49 XXXXX REACH
2024/10/01 02:17:49 XXXXX REACH
2024/10/01 02:17:49 Hit times: 18
2024/10/01 02:17:49 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:17:56 candidates=0 corpus=1723 coverage=36634 exec total=53038 (24/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:18:06 candidates=0 corpus=1723 coverage=36634 exec total=53038 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:18:16 candidates=0 corpus=1723 coverage=36634 exec total=53038 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:18:26 candidates=0 corpus=1723 coverage=36634 exec total=53038 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:18:30 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:18:36 candidates=0 corpus=1731 coverage=36669 exec total=53275 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:18:46 candidates=0 corpus=1748 coverage=36817 exec total=53867 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:18:56 candidates=0 corpus=1750 coverage=36821 exec total=53919 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:19:06 candidates=0 corpus=1764 coverage=36841 exec total=54243 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:19:16 candidates=0 corpus=1766 coverage=36841 exec total=54290 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:19:26 candidates=0 corpus=1768 coverage=36845 exec total=54346 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:19:36 candidates=0 corpus=1769 coverage=36845 exec total=54397 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:19:46 candidates=0 corpus=1774 coverage=36879 exec total=54505 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:19:56 candidates=0 corpus=1777 coverage=36889 exec total=54574 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:20:06 candidates=0 corpus=1787 coverage=37015 exec total=54865 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:20:16 candidates=0 corpus=1794 coverage=37054 exec total=55138 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:20:26 candidates=0 corpus=1824 coverage=37368 exec total=55999 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:20:36 candidates=0 corpus=1825 coverage=37370 exec total=56027 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:20:46 candidates=0 corpus=1809 coverage=37427 exec total=56049 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:20:56 candidates=0 corpus=1809 coverage=37427 exec total=56067 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:21:06 candidates=0 corpus=1809 coverage=37427 exec total=56087 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:21:16 candidates=0 corpus=1810 coverage=37429 exec total=56106 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:21:26 candidates=0 corpus=1812 coverage=37432 exec total=56146 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:21:36 candidates=0 corpus=1813 coverage=37437 exec total=56181 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:21:46 candidates=0 corpus=1815 coverage=37471 exec total=56218 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:21:56 candidates=0 corpus=1815 coverage=37471 exec total=56241 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:22:06 candidates=0 corpus=1815 coverage=37471 exec total=56268 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:22:16 candidates=0 corpus=1816 coverage=37479 exec total=56553 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:22:26 candidates=0 corpus=1827 coverage=37553 exec total=57060 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:22:36 candidates=0 corpus=1844 coverage=37633 exec total=57419 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:22:41 XXXXX REACH
2024/10/01 02:22:41 XXXXX REACH
2024/10/01 02:22:41 XXXXX REACH
2024/10/01 02:22:41 XXXXX REACH
2024/10/01 02:22:41 XXXXX REACH
2024/10/01 02:22:41 XXXXX REACH
2024/10/01 02:22:41 XXXXX REACH
2024/10/01 02:22:41 XXXXX REACH
2024/10/01 02:22:41 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:42 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:43 XXXXX REACH
2024/10/01 02:22:46 candidates=0 corpus=1858 coverage=37714 exec total=57879 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:22:46 XXXXX REACH
2024/10/01 02:22:46 XXXXX REACH
2024/10/01 02:22:47 Hit times: 38
2024/10/01 02:22:47 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:22:56 candidates=0 corpus=1858 coverage=37714 exec total=57879 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:23:06 candidates=0 corpus=1858 coverage=37714 exec total=57879 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:23:16 candidates=0 corpus=1858 coverage=37714 exec total=57879 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:23:26 candidates=0 corpus=1858 coverage=37714 exec total=57879 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:23:28 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:23:36 candidates=0 corpus=1859 coverage=37714 exec total=57917 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:23:46 candidates=0 corpus=1860 coverage=37714 exec total=57960 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:23:56 candidates=0 corpus=1884 coverage=37810 exec total=58539 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:24:06 candidates=0 corpus=1889 coverage=37814 exec total=58702 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:24:16 candidates=0 corpus=1906 coverage=38048 exec total=59267 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:24:26 candidates=0 corpus=1917 coverage=38135 exec total=59525 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:24:36 candidates=0 corpus=1932 coverage=38219 exec total=59958 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:24:46 candidates=0 corpus=1926 coverage=38254 exec total=60400 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:24:56 candidates=0 corpus=1947 coverage=38341 exec total=61171 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:25:06 candidates=0 corpus=1960 coverage=38396 exec total=61625 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:25:16 candidates=0 corpus=1970 coverage=38464 exec total=62047 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:25:26 candidates=0 corpus=1997 coverage=38584 exec total=62833 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:25:36 candidates=0 corpus=2001 coverage=38715 exec total=62943 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:25:46 candidates=0 corpus=1986 coverage=38758 exec total=63172 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:25:56 candidates=0 corpus=2010 coverage=38822 exec total=63838 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:26:06 candidates=0 corpus=2017 coverage=38864 exec total=64040 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:26:16 candidates=0 corpus=2017 coverage=38864 exec total=64076 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:26:26 candidates=0 corpus=2030 coverage=38948 exec total=64441 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:26:36 candidates=0 corpus=2034 coverage=38983 exec total=64539 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:26:37 XXXXX REACH
2024/10/01 02:26:37 XXXXX REACH
2024/10/01 02:26:37 XXXXX REACH
2024/10/01 02:26:37 XXXXX REACH
2024/10/01 02:26:37 XXXXX REACH
2024/10/01 02:26:37 XXXXX REACH
2024/10/01 02:26:37 XXXXX REACH
2024/10/01 02:26:38 XXXXX REACH
2024/10/01 02:26:38 XXXXX REACH
2024/10/01 02:26:39 XXXXX REACH
2024/10/01 02:26:39 XXXXX REACH
2024/10/01 02:26:39 XXXXX REACH
2024/10/01 02:26:39 XXXXX REACH
2024/10/01 02:26:39 XXXXX REACH
2024/10/01 02:26:39 XXXXX REACH
2024/10/01 02:26:39 XXXXX REACH
2024/10/01 02:26:40 XXXXX REACH
2024/10/01 02:26:40 XXXXX REACH
2024/10/01 02:26:40 XXXXX REACH
2024/10/01 02:26:40 XXXXX REACH
2024/10/01 02:26:41 XXXXX REACH
2024/10/01 02:26:41 XXXXX REACH
2024/10/01 02:26:41 XXXXX REACH
2024/10/01 02:26:41 XXXXX REACH
2024/10/01 02:26:41 XXXXX REACH
2024/10/01 02:26:41 XXXXX REACH
2024/10/01 02:26:41 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:42 XXXXX REACH
2024/10/01 02:26:43 Hit times: 38
2024/10/01 02:26:43 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:26:46 candidates=0 corpus=2024 coverage=38991 exec total=64590 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:26:56 candidates=0 corpus=2024 coverage=38991 exec total=64590 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:27:06 candidates=0 corpus=2024 coverage=38991 exec total=64590 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:27:16 candidates=0 corpus=2024 coverage=38991 exec total=64590 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:27:25 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:27:26 candidates=0 corpus=2032 coverage=39028 exec total=64838 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:27:36 candidates=0 corpus=2041 coverage=39036 exec total=65267 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:27:46 candidates=0 corpus=2054 coverage=39059 exec total=65647 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:27:56 candidates=0 corpus=2066 coverage=39084 exec total=66137 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:28:03 update choice table with LLM
2024/10/01 02:28:03 UpdateChoiceTable using LLM comm content
2024/10/01 02:28:03 Build Choice Table with LLM
2024/10/01 02:28:06 candidates=0 corpus=2072 coverage=39102 exec total=66482 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:28:16 candidates=0 corpus=2074 coverage=39103 exec total=66596 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:28:26 candidates=0 corpus=2078 coverage=39121 exec total=66768 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:28:36 candidates=0 corpus=2082 coverage=39128 exec total=66966 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:28:46 candidates=0 corpus=2084 coverage=39136 exec total=67011 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:28:56 candidates=0 corpus=2087 coverage=39257 exec total=67333 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:29:06 candidates=0 corpus=2095 coverage=39304 exec total=67716 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:29:16 candidates=0 corpus=2102 coverage=39312 exec total=68012 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:29:26 candidates=0 corpus=2105 coverage=39313 exec total=68151 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:29:36 candidates=0 corpus=2116 coverage=39350 exec total=68416 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:29:46 candidates=0 corpus=2103 coverage=39395 exec total=68735 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:29:56 candidates=0 corpus=2112 coverage=39409 exec total=69151 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:30:05 XXXXX REACH
2024/10/01 02:30:05 XXXXX REACH
2024/10/01 02:30:05 XXXXX REACH
2024/10/01 02:30:05 XXXXX REACH
2024/10/01 02:30:06 XXXXX REACH
2024/10/01 02:30:06 XXXXX REACH
2024/10/01 02:30:06 candidates=0 corpus=2128 coverage=39547 exec total=69879 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:30:06 XXXXX REACH
2024/10/01 02:30:06 XXXXX REACH
2024/10/01 02:30:06 XXXXX REACH
2024/10/01 02:30:06 XXXXX REACH
2024/10/01 02:30:06 XXXXX REACH
2024/10/01 02:30:07 XXXXX REACH
2024/10/01 02:30:07 XXXXX REACH
2024/10/01 02:30:07 XXXXX REACH
2024/10/01 02:30:07 XXXXX REACH
2024/10/01 02:30:07 XXXXX REACH
2024/10/01 02:30:07 XXXXX REACH
2024/10/01 02:30:07 XXXXX REACH
2024/10/01 02:30:08 XXXXX REACH
2024/10/01 02:30:08 XXXXX REACH
2024/10/01 02:30:08 XXXXX REACH
2024/10/01 02:30:08 XXXXX REACH
2024/10/01 02:30:08 XXXXX REACH
2024/10/01 02:30:08 XXXXX REACH
2024/10/01 02:30:09 XXXXX REACH
2024/10/01 02:30:09 XXXXX REACH
2024/10/01 02:30:09 XXXXX REACH
2024/10/01 02:30:09 XXXXX REACH
2024/10/01 02:30:09 XXXXX REACH
2024/10/01 02:30:10 XXXXX REACH
2024/10/01 02:30:10 XXXXX REACH
2024/10/01 02:30:10 XXXXX REACH
2024/10/01 02:30:10 XXXXX REACH
2024/10/01 02:30:10 XXXXX REACH
2024/10/01 02:30:10 XXXXX REACH
2024/10/01 02:30:10 XXXXX REACH
2024/10/01 02:30:10 XXXXX REACH
2024/10/01 02:30:11 XXXXX REACH
2024/10/01 02:30:11 XXXXX REACH
2024/10/01 02:30:11 Hit times: 39
2024/10/01 02:30:11 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:30:16 candidates=0 corpus=2128 coverage=39547 exec total=69879 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:30:26 candidates=0 corpus=2128 coverage=39547 exec total=69879 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:30:36 candidates=0 corpus=2128 coverage=39547 exec total=69879 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:30:46 candidates=0 corpus=2128 coverage=39547 exec total=69879 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:30:53 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:30:56 candidates=0 corpus=2136 coverage=39569 exec total=70101 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:31:06 candidates=0 corpus=2148 coverage=39687 exec total=70537 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:31:16 candidates=0 corpus=2152 coverage=39696 exec total=70732 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:31:26 candidates=0 corpus=2156 coverage=39911 exec total=70789 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:31:36 candidates=0 corpus=2160 coverage=39925 exec total=70923 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:31:46 candidates=0 corpus=2144 coverage=39960 exec total=71028 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:31:56 candidates=0 corpus=2147 coverage=39985 exec total=71098 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:32:06 candidates=0 corpus=2170 coverage=40106 exec total=72178 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:32:16 candidates=0 corpus=2187 coverage=40186 exec total=73084 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:32:26 candidates=0 corpus=2197 coverage=40220 exec total=73379 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:32:36 candidates=0 corpus=2199 coverage=40222 exec total=73552 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:32:46 candidates=0 corpus=2206 coverage=40299 exec total=74068 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:32:56 candidates=0 corpus=2211 coverage=40503 exec total=74215 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:33:06 candidates=0 corpus=2218 coverage=40561 exec total=74621 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:33:16 candidates=0 corpus=2220 coverage=40562 exec total=74705 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:33:26 candidates=0 corpus=2223 coverage=40566 exec total=74753 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:33:36 candidates=0 corpus=2225 coverage=40569 exec total=74802 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:33:46 candidates=0 corpus=2204 coverage=40569 exec total=74842 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:33:56 candidates=0 corpus=2206 coverage=40575 exec total=74884 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:34:06 candidates=0 corpus=2206 coverage=40575 exec total=74933 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:34:16 candidates=0 corpus=2208 coverage=40580 exec total=75058 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:34:26 candidates=0 corpus=2220 coverage=40627 exec total=75484 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:34:36 candidates=0 corpus=2238 coverage=40740 exec total=76137 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:34:46 candidates=0 corpus=2243 coverage=40827 exec total=76273 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:34:56 candidates=0 corpus=2244 coverage=40828 exec total=76317 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:35:06 candidates=0 corpus=2246 coverage=40840 exec total=76358 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:35:16 candidates=0 corpus=2247 coverage=40840 exec total=76389 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:35:25 XXXXX REACH
2024/10/01 02:35:25 XXXXX REACH
2024/10/01 02:35:26 XXXXX REACH
2024/10/01 02:35:26 XXXXX REACH
2024/10/01 02:35:26 XXXXX REACH
2024/10/01 02:35:26 candidates=0 corpus=2248 coverage=40841 exec total=76426 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:35:27 XXXXX REACH
2024/10/01 02:35:27 XXXXX REACH
2024/10/01 02:35:27 XXXXX REACH
2024/10/01 02:35:28 XXXXX REACH
2024/10/01 02:35:28 XXXXX REACH
2024/10/01 02:35:28 XXXXX REACH
2024/10/01 02:35:28 XXXXX REACH
2024/10/01 02:35:28 XXXXX REACH
2024/10/01 02:35:28 XXXXX REACH
2024/10/01 02:35:29 XXXXX REACH
2024/10/01 02:35:29 XXXXX REACH
2024/10/01 02:35:29 XXXXX REACH
2024/10/01 02:35:29 XXXXX REACH
2024/10/01 02:35:29 XXXXX REACH
2024/10/01 02:35:29 XXXXX REACH
2024/10/01 02:35:29 XXXXX REACH
2024/10/01 02:35:29 XXXXX REACH
2024/10/01 02:35:29 XXXXX REACH
2024/10/01 02:35:30 XXXXX REACH
2024/10/01 02:35:30 XXXXX REACH
2024/10/01 02:35:31 XXXXX REACH
2024/10/01 02:35:31 XXXXX REACH
2024/10/01 02:35:31 XXXXX REACH
2024/10/01 02:35:31 XXXXX REACH
2024/10/01 02:35:31 XXXXX REACH
2024/10/01 02:35:31 XXXXX REACH
2024/10/01 02:35:31 XXXXX REACH
2024/10/01 02:35:31 XXXXX REACH
2024/10/01 02:35:31 XXXXX REACH
2024/10/01 02:35:32 Hit times: 34
2024/10/01 02:35:32 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:35:36 candidates=0 corpus=2248 coverage=40841 exec total=76426 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:35:46 candidates=0 corpus=2248 coverage=40841 exec total=76426 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:35:56 candidates=0 corpus=2248 coverage=40841 exec total=76426 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:36:06 candidates=0 corpus=2248 coverage=40841 exec total=76426 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:36:13 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:36:16 candidates=0 corpus=2248 coverage=40841 exec total=76438 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:36:26 candidates=0 corpus=2248 coverage=40841 exec total=76482 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:36:36 candidates=0 corpus=2250 coverage=40844 exec total=76523 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:36:46 candidates=0 corpus=2251 coverage=40855 exec total=76563 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:36:56 candidates=0 corpus=2255 coverage=40868 exec total=76668 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:37:06 candidates=0 corpus=2260 coverage=40878 exec total=76788 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:37:16 candidates=0 corpus=2280 coverage=40995 exec total=77386 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:37:26 candidates=0 corpus=2283 coverage=40999 exec total=77534 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:37:36 candidates=0 corpus=2287 coverage=41016 exec total=77682 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:37:46 candidates=0 corpus=2284 coverage=41043 exec total=77879 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:37:56 candidates=0 corpus=2294 coverage=41313 exec total=78316 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:38:06 candidates=0 corpus=2309 coverage=41343 exec total=78884 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:38:16 candidates=0 corpus=2318 coverage=41363 exec total=79247 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:38:26 candidates=0 corpus=2329 coverage=41482 exec total=79588 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:38:36 candidates=0 corpus=2348 coverage=41634 exec total=80166 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:38:46 candidates=0 corpus=2373 coverage=41990 exec total=81108 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:38:56 candidates=0 corpus=2377 coverage=41996 exec total=81194 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:39:06 candidates=0 corpus=2377 coverage=41996 exec total=81222 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:39:16 candidates=0 corpus=2385 coverage=42020 exec total=81530 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:39:26 update choice table with LLM
2024/10/01 02:39:26 UpdateChoiceTable using LLM comm content
2024/10/01 02:39:26 Build Choice Table with LLM
2024/10/01 02:39:26 candidates=0 corpus=2406 coverage=42065 exec total=82228 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:27 XXXXX REACH
2024/10/01 02:39:28 XXXXX REACH
2024/10/01 02:39:28 XXXXX REACH
2024/10/01 02:39:30 XXXXX REACH
2024/10/01 02:39:30 XXXXX REACH
2024/10/01 02:39:30 XXXXX REACH
2024/10/01 02:39:30 XXXXX REACH
2024/10/01 02:39:32 XXXXX REACH
2024/10/01 02:39:32 XXXXX REACH
2024/10/01 02:39:32 XXXXX REACH
2024/10/01 02:39:32 XXXXX REACH
2024/10/01 02:39:33 Hit times: 22
2024/10/01 02:39:33 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:39:36 candidates=0 corpus=2406 coverage=42065 exec total=82258 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:39:46 candidates=0 corpus=2406 coverage=42065 exec total=82258 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:39:56 candidates=0 corpus=2406 coverage=42065 exec total=82258 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:40:06 candidates=0 corpus=2406 coverage=42065 exec total=82258 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:40:13 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:40:16 candidates=0 corpus=2410 coverage=42083 exec total=82422 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:40:26 candidates=0 corpus=2412 coverage=42093 exec total=82462 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:40:36 candidates=0 corpus=2414 coverage=42105 exec total=82507 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:40:46 candidates=0 corpus=2435 coverage=42257 exec total=83092 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:40:56 candidates=0 corpus=2444 coverage=42271 exec total=83454 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:41:06 candidates=0 corpus=2450 coverage=42287 exec total=83806 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:41:16 candidates=0 corpus=2457 coverage=42306 exec total=84089 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:41:26 candidates=0 corpus=2466 coverage=42334 exec total=84461 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:41:27 vm-1: running for 1h0m0.001527469s, restarting
2024/10/01 02:41:36 candidates=0 corpus=2467 coverage=42344 exec total=84484 (23/sec) fuzzing VMs=0 reproducing=0 
2024/10/01 02:41:37 XXX Fuzzer command: 
/syz-fuzzer -executor=/syz-executor -name=vm-2 -arch=amd64 -manager=localhost:45263 -sandbox=none -cover=true -debug=false  -optional=slowdown=1:sandbox_arg=0:pprof_port=6060
2024/10/01 02:41:46 candidates=0 corpus=2447 coverage=42364 exec total=84702 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:41:56 candidates=0 corpus=2458 coverage=42391 exec total=85020 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:42:06 candidates=0 corpus=2483 coverage=42512 exec total=85840 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:42:16 candidates=0 corpus=2495 coverage=42589 exec total=86279 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:42:26 candidates=0 corpus=2504 coverage=42612 exec total=86536 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:42:36 candidates=0 corpus=2507 coverage=42647 exec total=86643 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:42:46 candidates=0 corpus=2510 coverage=42658 exec total=86754 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:42:56 candidates=0 corpus=2510 coverage=42658 exec total=86780 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:43:06 candidates=0 corpus=2510 coverage=42658 exec total=86804 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:43:16 candidates=0 corpus=2518 coverage=42671 exec total=86987 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:43:26 candidates=0 corpus=2520 coverage=42676 exec total=87031 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:43:36 candidates=0 corpus=2520 coverage=42676 exec total=87065 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:43:46 candidates=0 corpus=2509 coverage=42676 exec total=87146 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:43:56 candidates=0 corpus=2516 coverage=42695 exec total=87387 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:44:06 candidates=0 corpus=2516 coverage=42695 exec total=87442 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:44:16 candidates=0 corpus=2517 coverage=42695 exec total=87494 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:44:26 candidates=0 corpus=2518 coverage=42712 exec total=87538 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:44:36 candidates=0 corpus=2533 coverage=42777 exec total=88225 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:44:46 candidates=0 corpus=2539 coverage=42783 exec total=88441 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:44:56 candidates=0 corpus=2540 coverage=42783 exec total=88488 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:45:06 candidates=0 corpus=2543 coverage=42787 exec total=88588 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:45:16 candidates=0 corpus=2556 coverage=42859 exec total=89130 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:45:26 candidates=0 corpus=2560 coverage=42876 exec total=89357 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:45:36 candidates=0 corpus=2560 coverage=42876 exec total=89380 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:45:46 candidates=0 corpus=2560 coverage=42876 exec total=89404 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:45:56 candidates=0 corpus=2561 coverage=42900 exec total=89428 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:46:06 candidates=0 corpus=2566 coverage=42909 exec total=89575 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:10 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:11 XXXXX REACH
2024/10/01 02:46:12 XXXXX REACH
2024/10/01 02:46:12 XXXXX REACH
2024/10/01 02:46:12 XXXXX REACH
2024/10/01 02:46:12 XXXXX REACH
2024/10/01 02:46:12 XXXXX REACH
2024/10/01 02:46:13 XXXXX REACH
2024/10/01 02:46:13 XXXXX REACH
2024/10/01 02:46:13 XXXXX REACH
2024/10/01 02:46:13 XXXXX REACH
2024/10/01 02:46:13 XXXXX REACH
2024/10/01 02:46:13 XXXXX REACH
2024/10/01 02:46:13 XXXXX REACH
2024/10/01 02:46:14 XXXXX REACH
2024/10/01 02:46:14 XXXXX REACH
2024/10/01 02:46:14 XXXXX REACH
2024/10/01 02:46:14 XXXXX REACH
2024/10/01 02:46:14 XXXXX REACH
2024/10/01 02:46:14 XXXXX REACH
2024/10/01 02:46:14 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:15 XXXXX REACH
2024/10/01 02:46:16 Hit times: 65
2024/10/01 02:46:16 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:46:16 candidates=0 corpus=2571 coverage=42915 exec total=89715 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:46:26 candidates=0 corpus=2571 coverage=42915 exec total=89715 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:46:36 candidates=0 corpus=2571 coverage=42915 exec total=89715 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:46:46 candidates=0 corpus=2571 coverage=42915 exec total=89715 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:46:56 candidates=0 corpus=2571 coverage=42915 exec total=89715 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:46:56 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:47:06 candidates=0 corpus=2588 coverage=42958 exec total=90188 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:47:16 candidates=0 corpus=2596 coverage=43010 exec total=90464 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:47:26 candidates=0 corpus=2596 coverage=43010 exec total=90533 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:47:36 candidates=0 corpus=2598 coverage=43016 exec total=90578 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:47:46 candidates=0 corpus=2590 coverage=43120 exec total=90905 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:47:56 candidates=0 corpus=2595 coverage=43127 exec total=91115 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:48:06 candidates=0 corpus=2606 coverage=43172 exec total=91424 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:48:16 candidates=0 corpus=2611 coverage=43199 exec total=91566 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:48:26 candidates=0 corpus=2613 coverage=43261 exec total=91634 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:48:36 candidates=0 corpus=2619 coverage=43388 exec total=91718 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:48:46 candidates=0 corpus=2634 coverage=43509 exec total=92177 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:48:56 candidates=0 corpus=2655 coverage=43641 exec total=92831 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:49:06 candidates=0 corpus=2668 coverage=43775 exec total=93310 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:49:16 candidates=0 corpus=2674 coverage=43796 exec total=93588 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:49:26 candidates=0 corpus=2693 coverage=43889 exec total=94239 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:49:36 candidates=0 corpus=2709 coverage=43935 exec total=94771 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:49:46 candidates=0 corpus=2702 coverage=44022 exec total=95345 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:49:56 candidates=0 corpus=2720 coverage=44119 exec total=96024 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:50:05 XXXXX REACH
2024/10/01 02:50:05 XXXXX REACH
2024/10/01 02:50:06 XXXXX REACH
2024/10/01 02:50:06 XXXXX REACH
2024/10/01 02:50:06 candidates=0 corpus=2728 coverage=44189 exec total=96299 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:50:06 XXXXX REACH
2024/10/01 02:50:06 XXXXX REACH
2024/10/01 02:50:07 XXXXX REACH
2024/10/01 02:50:07 XXXXX REACH
2024/10/01 02:50:08 XXXXX REACH
2024/10/01 02:50:08 XXXXX REACH
2024/10/01 02:50:08 XXXXX REACH
2024/10/01 02:50:08 XXXXX REACH
2024/10/01 02:50:08 XXXXX REACH
2024/10/01 02:50:08 XXXXX REACH
2024/10/01 02:50:08 XXXXX REACH
2024/10/01 02:50:09 XXXXX REACH
2024/10/01 02:50:09 XXXXX REACH
2024/10/01 02:50:09 XXXXX REACH
2024/10/01 02:50:09 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:10 XXXXX REACH
2024/10/01 02:50:11 XXXXX REACH
2024/10/01 02:50:11 XXXXX REACH
2024/10/01 02:50:11 XXXXX REACH
2024/10/01 02:50:11 Hit times: 59
2024/10/01 02:50:11 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:50:16 candidates=0 corpus=2728 coverage=44189 exec total=96299 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:50:26 candidates=0 corpus=2728 coverage=44189 exec total=96299 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:50:36 candidates=0 corpus=2728 coverage=44189 exec total=96299 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:50:46 candidates=0 corpus=2728 coverage=44189 exec total=96299 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:50:53 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:50:56 update choice table with LLM
2024/10/01 02:50:56 UpdateChoiceTable using LLM comm content
2024/10/01 02:50:56 Build Choice Table with LLM
2024/10/01 02:50:56 candidates=0 corpus=2740 coverage=44262 exec total=96696 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:51:06 candidates=0 corpus=2744 coverage=44268 exec total=96936 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:51:16 candidates=0 corpus=2753 coverage=44309 exec total=97419 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:51:26 candidates=0 corpus=2759 coverage=44373 exec total=97705 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:51:36 candidates=0 corpus=2766 coverage=44404 exec total=98010 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:51:46 candidates=0 corpus=2775 coverage=44411 exec total=98531 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:51:56 candidates=0 corpus=2786 coverage=44458 exec total=98951 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:52:06 candidates=0 corpus=2798 coverage=44500 exec total=99235 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:52:16 candidates=0 corpus=2798 coverage=44500 exec total=99290 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:52:26 candidates=0 corpus=2804 coverage=44508 exec total=99487 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:52:36 candidates=0 corpus=2820 coverage=44591 exec total=99945 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:52:46 candidates=0 corpus=2795 coverage=44595 exec total=100105 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:52:56 candidates=0 corpus=2796 coverage=44596 exec total=100152 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:53:06 candidates=0 corpus=2804 coverage=44611 exec total=100377 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:53:16 candidates=0 corpus=2807 coverage=44615 exec total=100505 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:53:26 candidates=0 corpus=2816 coverage=44651 exec total=100858 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:53:36 candidates=0 corpus=2824 coverage=44671 exec total=101000 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:53:46 candidates=0 corpus=2824 coverage=44671 exec total=101052 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:53:56 candidates=0 corpus=2835 coverage=44757 exec total=101260 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:54:06 candidates=0 corpus=2843 coverage=44785 exec total=101628 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:54:16 candidates=0 corpus=2850 coverage=44806 exec total=101872 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:54:26 candidates=0 corpus=2869 coverage=44817 exec total=102622 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:54:36 candidates=0 corpus=2870 coverage=44817 exec total=102695 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:54:46 candidates=0 corpus=2870 coverage=44817 exec total=102739 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:54:56 candidates=0 corpus=2886 coverage=44931 exec total=103385 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:55:06 candidates=0 corpus=2898 coverage=44955 exec total=103993 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:55:16 candidates=0 corpus=2912 coverage=45013 exec total=104552 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:55:16 XXXXX REACH
2024/10/01 02:55:16 XXXXX REACH
2024/10/01 02:55:16 XXXXX REACH
2024/10/01 02:55:16 XXXXX REACH
2024/10/01 02:55:16 XXXXX REACH
2024/10/01 02:55:16 XXXXX REACH
2024/10/01 02:55:17 XXXXX REACH
2024/10/01 02:55:17 XXXXX REACH
2024/10/01 02:55:17 XXXXX REACH
2024/10/01 02:55:18 XXXXX REACH
2024/10/01 02:55:18 XXXXX REACH
2024/10/01 02:55:18 XXXXX REACH
2024/10/01 02:55:18 XXXXX REACH
2024/10/01 02:55:18 XXXXX REACH
2024/10/01 02:55:18 XXXXX REACH
2024/10/01 02:55:18 XXXXX REACH
2024/10/01 02:55:18 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:19 XXXXX REACH
2024/10/01 02:55:20 XXXXX REACH
2024/10/01 02:55:20 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:21 XXXXX REACH
2024/10/01 02:55:22 XXXXX REACH
2024/10/01 02:55:22 XXXXX REACH
2024/10/01 02:55:22 XXXXX REACH
2024/10/01 02:55:22 XXXXX REACH
2024/10/01 02:55:22 Hit times: 65
2024/10/01 02:55:22 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 02:55:26 candidates=0 corpus=2912 coverage=45013 exec total=104552 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:55:36 candidates=0 corpus=2912 coverage=45013 exec total=104552 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:55:46 candidates=0 corpus=2891 coverage=45013 exec total=104552 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:55:56 candidates=0 corpus=2891 coverage=45013 exec total=104552 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:56:03 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 02:56:06 candidates=0 corpus=2893 coverage=45016 exec total=104597 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:56:16 candidates=0 corpus=2912 coverage=45380 exec total=105138 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:56:26 candidates=0 corpus=2919 coverage=45435 exec total=105492 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:56:36 candidates=0 corpus=2922 coverage=45438 exec total=105562 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:56:46 candidates=0 corpus=2924 coverage=45439 exec total=105621 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:56:56 candidates=0 corpus=2933 coverage=45512 exec total=105899 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:57:06 candidates=0 corpus=2935 coverage=45516 exec total=105974 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:57:16 candidates=0 corpus=2935 coverage=45516 exec total=105974 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:57:26 candidates=0 corpus=2935 coverage=45516 exec total=105974 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:57:36 candidates=0 corpus=2936 coverage=45516 exec total=106052 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:57:46 candidates=0 corpus=2941 coverage=45566 exec total=106259 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:57:56 candidates=0 corpus=2944 coverage=45569 exec total=106307 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:58:06 candidates=0 corpus=2944 coverage=45569 exec total=106324 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:58:16 candidates=0 corpus=2945 coverage=45569 exec total=106341 (23/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:58:26 candidates=0 corpus=2945 coverage=45569 exec total=106360 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:58:36 candidates=0 corpus=2945 coverage=45569 exec total=106382 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:58:46 candidates=0 corpus=2945 coverage=45569 exec total=106404 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:58:56 candidates=0 corpus=2946 coverage=45569 exec total=106420 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:59:06 candidates=0 corpus=2946 coverage=45569 exec total=106435 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:59:16 candidates=0 corpus=2946 coverage=45569 exec total=106449 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:59:26 candidates=0 corpus=2946 coverage=45569 exec total=106465 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:59:36 candidates=0 corpus=2946 coverage=45569 exec total=106484 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:59:46 candidates=0 corpus=2946 coverage=45569 exec total=106505 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 02:59:56 candidates=0 corpus=2947 coverage=45569 exec total=106527 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:00:06 candidates=0 corpus=2947 coverage=45569 exec total=106549 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:00:16 candidates=0 corpus=2947 coverage=45569 exec total=106569 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:00:26 candidates=0 corpus=2947 coverage=45569 exec total=106580 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:00:36 candidates=0 corpus=2948 coverage=46344 exec total=106592 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:00:46 candidates=0 corpus=2948 coverage=46344 exec total=106603 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:00:56 candidates=0 corpus=2949 coverage=46348 exec total=106615 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:01:06 candidates=0 corpus=2949 coverage=46348 exec total=106626 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:01:16 candidates=0 corpus=2949 coverage=46348 exec total=106639 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:01:26 candidates=0 corpus=2949 coverage=46348 exec total=106660 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:01:36 candidates=0 corpus=2949 coverage=46348 exec total=106683 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:01:46 candidates=0 corpus=2949 coverage=46348 exec total=106707 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:01:56 candidates=0 corpus=2949 coverage=46348 exec total=106729 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:02:06 candidates=0 corpus=2949 coverage=46348 exec total=106753 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:02:16 candidates=0 corpus=2951 coverage=46513 exec total=106781 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:02:26 candidates=0 corpus=2951 coverage=46513 exec total=106805 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:02:36 candidates=0 corpus=2952 coverage=46529 exec total=106838 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:02:46 candidates=0 corpus=2955 coverage=46831 exec total=106949 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:02:56 candidates=0 corpus=2962 coverage=46872 exec total=107213 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:03:06 candidates=0 corpus=2979 coverage=46882 exec total=107904 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:03:16 candidates=0 corpus=2992 coverage=46933 exec total=108498 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:03:26 candidates=0 corpus=3000 coverage=46945 exec total=108842 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:03:36 candidates=0 corpus=3015 coverage=46963 exec total=109532 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:03:46 candidates=0 corpus=3002 coverage=47240 exec total=110436 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:03:56 candidates=0 corpus=3013 coverage=47244 exec total=110846 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:04:06 candidates=0 corpus=3030 coverage=47309 exec total=111674 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:04:16 candidates=0 corpus=3033 coverage=47311 exec total=111828 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:04:26 candidates=0 corpus=3035 coverage=47311 exec total=111896 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:04:36 candidates=0 corpus=3035 coverage=47311 exec total=111947 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:04:46 candidates=0 corpus=3036 coverage=47311 exec total=112005 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:04:56 candidates=0 corpus=3038 coverage=47312 exec total=112045 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:05:06 candidates=0 corpus=3039 coverage=47312 exec total=112135 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:05:16 candidates=0 corpus=3040 coverage=47709 exec total=112179 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:05:26 candidates=0 corpus=3040 coverage=47709 exec total=112206 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:05:36 candidates=0 corpus=3040 coverage=47709 exec total=112231 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:05:46 candidates=0 corpus=3040 coverage=47709 exec total=112254 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:05:56 candidates=0 corpus=3042 coverage=47764 exec total=112283 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:06:06 candidates=0 corpus=3042 coverage=47764 exec total=112319 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:06:16 candidates=0 corpus=3042 coverage=47764 exec total=112347 (22/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:06:26 candidates=0 corpus=3043 coverage=47798 exec total=112372 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:06:36 candidates=0 corpus=3043 coverage=47798 exec total=112398 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:06:46 candidates=0 corpus=3044 coverage=47801 exec total=112475 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:06:56 candidates=0 corpus=3046 coverage=47801 exec total=112494 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:07:06 candidates=0 corpus=3046 coverage=47801 exec total=112513 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:07:16 candidates=0 corpus=3046 coverage=47801 exec total=112537 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:07:26 candidates=0 corpus=3046 coverage=47801 exec total=112563 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:07:36 candidates=0 corpus=3046 coverage=47801 exec total=112588 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:07:46 candidates=0 corpus=3046 coverage=47801 exec total=112606 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:07:56 candidates=0 corpus=3046 coverage=47801 exec total=112634 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:08:06 candidates=0 corpus=3046 coverage=47801 exec total=112665 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:08:16 candidates=0 corpus=3047 coverage=47805 exec total=112696 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:17 XXXXX REACH
2024/10/01 03:08:18 XXXXX REACH
2024/10/01 03:08:18 XXXXX REACH
2024/10/01 03:08:18 XXXXX REACH
2024/10/01 03:08:18 XXXXX REACH
2024/10/01 03:08:20 XXXXX REACH
2024/10/01 03:08:20 XXXXX REACH
2024/10/01 03:08:20 XXXXX REACH
2024/10/01 03:08:21 XXXXX REACH
2024/10/01 03:08:21 XXXXX REACH
2024/10/01 03:08:21 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:22 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 XXXXX REACH
2024/10/01 03:08:23 Hit times: 41
2024/10/01 03:08:23 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 03:08:26 candidates=0 corpus=3047 coverage=47805 exec total=112697 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:08:36 candidates=0 corpus=3047 coverage=47805 exec total=112697 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:08:46 candidates=0 corpus=3047 coverage=47805 exec total=112697 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:08:56 candidates=0 corpus=3047 coverage=47805 exec total=112697 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:09:05 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 03:09:06 candidates=0 corpus=3047 coverage=47805 exec total=112703 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:09:16 candidates=0 corpus=3047 coverage=47805 exec total=112727 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:09:26 candidates=0 corpus=3049 coverage=47810 exec total=112752 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:09:36 candidates=0 corpus=3049 coverage=47810 exec total=112786 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:09:46 candidates=0 corpus=3049 coverage=47810 exec total=112810 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:09:56 candidates=0 corpus=3049 coverage=47810 exec total=112841 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:10:06 candidates=0 corpus=3049 coverage=47810 exec total=112865 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:10:16 candidates=0 corpus=3049 coverage=47810 exec total=112886 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:10:26 candidates=0 corpus=3051 coverage=47811 exec total=112953 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:10:36 candidates=0 corpus=3051 coverage=47811 exec total=113001 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:10:46 candidates=0 corpus=3052 coverage=47811 exec total=113045 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:10:56 candidates=0 corpus=3055 coverage=47811 exec total=113282 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:11:06 candidates=0 corpus=3056 coverage=47815 exec total=113365 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:11:16 candidates=0 corpus=3058 coverage=47815 exec total=113412 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:11:26 candidates=0 corpus=3061 coverage=47839 exec total=113602 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:11:35 update choice table with LLM
2024/10/01 03:11:35 UpdateChoiceTable using LLM comm content
2024/10/01 03:11:35 Build Choice Table with LLM
2024/10/01 03:11:36 candidates=0 corpus=3074 coverage=47853 exec total=114205 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:11:46 candidates=0 corpus=3053 coverage=47860 exec total=114637 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:11:56 candidates=0 corpus=3061 coverage=47963 exec total=115046 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:12:06 candidates=0 corpus=3063 coverage=47965 exec total=115129 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:12:16 candidates=0 corpus=3063 coverage=47965 exec total=115174 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:12:26 candidates=0 corpus=3064 coverage=47965 exec total=115215 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:12:36 candidates=0 corpus=3064 coverage=47965 exec total=115263 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:12:46 candidates=0 corpus=3065 coverage=47965 exec total=115321 (21/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:12:56 candidates=0 corpus=3066 coverage=47965 exec total=115369 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:13:06 candidates=0 corpus=3066 coverage=47965 exec total=115455 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:13:16 candidates=0 corpus=3067 coverage=47965 exec total=115486 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:13:26 candidates=0 corpus=3067 coverage=47965 exec total=115510 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:13:36 candidates=0 corpus=3067 coverage=47965 exec total=115534 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:13:46 candidates=0 corpus=3069 coverage=47973 exec total=115570 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:13:56 candidates=0 corpus=3069 coverage=47973 exec total=115608 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:14:06 candidates=0 corpus=3070 coverage=47973 exec total=115683 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:14:16 candidates=0 corpus=3070 coverage=47973 exec total=115721 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:14:26 candidates=0 corpus=3071 coverage=47973 exec total=115753 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:14:36 candidates=0 corpus=3073 coverage=47974 exec total=115775 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:14:46 candidates=0 corpus=3073 coverage=47974 exec total=115813 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:14:56 candidates=0 corpus=3073 coverage=47974 exec total=115854 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:15:06 candidates=0 corpus=3073 coverage=47974 exec total=115895 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:15:16 candidates=0 corpus=3073 coverage=47974 exec total=115928 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:15:26 candidates=0 corpus=3074 coverage=47975 exec total=115967 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:15:36 candidates=0 corpus=3074 coverage=47975 exec total=116002 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:15:46 candidates=0 corpus=3082 coverage=47989 exec total=116388 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:15:56 candidates=0 corpus=3094 coverage=48061 exec total=116862 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:16:06 candidates=0 corpus=3105 coverage=48175 exec total=117261 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:16:16 candidates=0 corpus=3117 coverage=48195 exec total=117986 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:16:26 candidates=0 corpus=3119 coverage=48195 exec total=118073 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:16:36 candidates=0 corpus=3120 coverage=48196 exec total=118117 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:16:46 candidates=0 corpus=3121 coverage=48263 exec total=118151 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:16:56 candidates=0 corpus=3121 coverage=48263 exec total=118175 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:17:06 candidates=0 corpus=3121 coverage=48263 exec total=118204 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:17:16 candidates=0 corpus=3122 coverage=48263 exec total=118239 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:17:26 candidates=0 corpus=3123 coverage=48264 exec total=118275 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:17:36 candidates=0 corpus=3123 coverage=48264 exec total=118324 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:17:46 candidates=0 corpus=3124 coverage=48264 exec total=118348 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:17:56 candidates=0 corpus=3124 coverage=48264 exec total=118372 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:18:06 candidates=0 corpus=3125 coverage=48264 exec total=118396 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:18:16 candidates=0 corpus=3126 coverage=48265 exec total=118447 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:18:26 candidates=0 corpus=3128 coverage=48272 exec total=118553 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:18:36 candidates=0 corpus=3129 coverage=48273 exec total=118664 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:18:46 candidates=0 corpus=3139 coverage=48294 exec total=118932 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:18:56 candidates=0 corpus=3142 coverage=48305 exec total=118987 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:19:06 candidates=0 corpus=3144 coverage=48308 exec total=119007 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:19:16 candidates=0 corpus=3144 coverage=48308 exec total=119031 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:19:26 candidates=0 corpus=3144 coverage=48308 exec total=119059 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:19:36 candidates=0 corpus=3144 coverage=48308 exec total=119102 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:19:46 candidates=0 corpus=3113 coverage=48308 exec total=119181 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:19:56 candidates=0 corpus=3126 coverage=48345 exec total=119591 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:20:06 candidates=0 corpus=3132 coverage=48367 exec total=119820 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:20:16 candidates=0 corpus=3143 coverage=48378 exec total=120211 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:20:26 candidates=0 corpus=3154 coverage=48492 exec total=120576 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:20:36 candidates=0 corpus=3158 coverage=48506 exec total=120720 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:20:46 candidates=0 corpus=3166 coverage=48519 exec total=120955 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:20:56 candidates=0 corpus=3181 coverage=48541 exec total=121503 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:21:06 candidates=0 corpus=3184 coverage=48555 exec total=121568 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:21:16 candidates=0 corpus=3185 coverage=48555 exec total=121599 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:21:26 candidates=0 corpus=3192 coverage=48597 exec total=121869 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:21:27 XXXXX REACH
2024/10/01 03:21:27 XXXXX REACH
2024/10/01 03:21:27 XXXXX REACH
2024/10/01 03:21:27 XXXXX REACH
2024/10/01 03:21:28 XXXXX REACH
2024/10/01 03:21:28 XXXXX REACH
2024/10/01 03:21:28 XXXXX REACH
2024/10/01 03:21:28 XXXXX REACH
2024/10/01 03:21:28 XXXXX REACH
2024/10/01 03:21:28 XXXXX REACH
2024/10/01 03:21:29 XXXXX REACH
2024/10/01 03:21:29 XXXXX REACH
2024/10/01 03:21:30 XXXXX REACH
2024/10/01 03:21:30 XXXXX REACH
2024/10/01 03:21:31 XXXXX REACH
2024/10/01 03:21:31 XXXXX REACH
2024/10/01 03:21:31 XXXXX REACH
2024/10/01 03:21:31 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:32 XXXXX REACH
2024/10/01 03:21:33 Hit times: 34
2024/10/01 03:21:33 process print: /usr/bin/python3 ./scripts/process_close_cov_result.py
2024/10/01 03:21:36 candidates=0 corpus=3192 coverage=48598 exec total=121919 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:21:46 candidates=0 corpus=3192 coverage=48598 exec total=121919 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:21:56 candidates=0 corpus=3192 coverage=48598 exec total=121919 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:22:06 candidates=0 corpus=3192 coverage=48598 exec total=121919 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:22:14 close ask
close ask Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 478, in <module>
    llm_list_result = interface.ask_for_syscalls_to_improve(target_function_list)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 155, in ask_for_syscalls_to_improve
    answer = self.ask_question_and_record(description)
  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 61, in ask_question_and_record
    res = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 997, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

close ask Output: 
2024/10/01 03:22:16 candidates=0 corpus=3196 coverage=48628 exec total=122021 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:22:26 candidates=0 corpus=3207 coverage=48679 exec total=122349 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:22:36 candidates=0 corpus=3211 coverage=48688 exec total=122522 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:22:46 candidates=0 corpus=3183 coverage=48736 exec total=122763 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:22:56 candidates=0 corpus=3189 coverage=48746 exec total=122941 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:23:06 candidates=0 corpus=3193 coverage=48751 exec total=123137 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:23:16 candidates=0 corpus=3201 coverage=48811 exec total=123373 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:23:26 candidates=0 corpus=3212 coverage=48847 exec total=123853 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:23:36 candidates=0 corpus=3225 coverage=48862 exec total=124211 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:23:46 candidates=0 corpus=3225 coverage=48862 exec total=124257 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:23:56 candidates=0 corpus=3228 coverage=48876 exec total=124348 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:24:06 candidates=0 corpus=3231 coverage=48880 exec total=124468 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:24:16 candidates=0 corpus=3252 coverage=48992 exec total=125088 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:24:26 candidates=0 corpus=3253 coverage=48992 exec total=125159 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:24:36 candidates=0 corpus=3254 coverage=48992 exec total=125194 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:24:46 candidates=0 corpus=3254 coverage=48992 exec total=125217 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:24:56 candidates=0 corpus=3255 coverage=48993 exec total=125236 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:25:06 candidates=0 corpus=3255 coverage=48993 exec total=125251 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:25:16 candidates=0 corpus=3256 coverage=48994 exec total=125266 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:25:26 candidates=0 corpus=3256 coverage=48994 exec total=125277 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:25:36 candidates=0 corpus=3256 coverage=48994 exec total=125289 (20/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:25:46 candidates=0 corpus=3256 coverage=48994 exec total=125300 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:25:56 candidates=0 corpus=3256 coverage=48994 exec total=125312 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:26:06 candidates=0 corpus=3256 coverage=48994 exec total=125323 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:26:16 candidates=0 corpus=3256 coverage=48994 exec total=125337 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:26:26 candidates=0 corpus=3256 coverage=48994 exec total=125348 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:26:36 candidates=0 corpus=3256 coverage=48994 exec total=125360 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:26:46 candidates=0 corpus=3256 coverage=48994 exec total=125372 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:26:56 candidates=0 corpus=3256 coverage=48994 exec total=125385 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:27:06 candidates=0 corpus=3256 coverage=48994 exec total=125397 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:27:16 candidates=0 corpus=3256 coverage=48994 exec total=125409 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:27:26 candidates=0 corpus=3256 coverage=48994 exec total=125422 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:27:36 candidates=0 corpus=3256 coverage=48994 exec total=125434 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:27:46 candidates=0 corpus=3256 coverage=48994 exec total=125446 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:27:56 candidates=0 corpus=3256 coverage=48994 exec total=125458 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:28:06 candidates=0 corpus=3256 coverage=48994 exec total=125469 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:28:16 candidates=0 corpus=3256 coverage=48994 exec total=125481 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:28:26 candidates=0 corpus=3256 coverage=48994 exec total=125492 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:28:36 candidates=0 corpus=3256 coverage=48994 exec total=125504 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:28:46 candidates=0 corpus=3256 coverage=48994 exec total=125515 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:28:56 candidates=0 corpus=3256 coverage=48994 exec total=125527 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:29:06 candidates=0 corpus=3256 coverage=48994 exec total=125539 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:29:16 candidates=0 corpus=3256 coverage=48994 exec total=125550 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:29:26 candidates=0 corpus=3256 coverage=48994 exec total=125562 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:29:36 candidates=0 corpus=3256 coverage=48994 exec total=125575 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:29:46 candidates=0 corpus=3256 coverage=48994 exec total=125587 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:29:56 candidates=0 corpus=3256 coverage=48994 exec total=125598 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:30:06 candidates=0 corpus=3256 coverage=48994 exec total=125610 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:30:16 candidates=0 corpus=3256 coverage=48994 exec total=125622 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:30:26 candidates=0 corpus=3256 coverage=48994 exec total=125633 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:30:36 candidates=0 corpus=3256 coverage=48994 exec total=125645 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:30:46 candidates=0 corpus=3256 coverage=48994 exec total=125657 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:30:56 candidates=0 corpus=3256 coverage=48994 exec total=125668 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:31:06 candidates=0 corpus=3256 coverage=48994 exec total=125680 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:31:16 candidates=0 corpus=3256 coverage=48994 exec total=125692 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:31:26 candidates=0 corpus=3256 coverage=48994 exec total=125703 (19/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:31:36 candidates=0 corpus=3256 coverage=48994 exec total=125715 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:31:46 candidates=0 corpus=3256 coverage=48994 exec total=125726 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:31:56 candidates=0 corpus=3256 coverage=48994 exec total=125737 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:32:06 candidates=0 corpus=3256 coverage=48994 exec total=125749 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:32:16 candidates=0 corpus=3256 coverage=48994 exec total=125760 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:32:26 candidates=0 corpus=3256 coverage=48994 exec total=125772 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:32:36 candidates=0 corpus=3256 coverage=48994 exec total=125783 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:32:46 candidates=0 corpus=3256 coverage=48994 exec total=125795 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:32:56 candidates=0 corpus=3256 coverage=48994 exec total=125807 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:33:06 candidates=0 corpus=3256 coverage=48994 exec total=125818 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:33:16 candidates=0 corpus=3256 coverage=48994 exec total=125830 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:33:26 candidates=0 corpus=3256 coverage=48994 exec total=125842 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:33:36 candidates=0 corpus=3256 coverage=48994 exec total=125853 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:33:46 candidates=0 corpus=3256 coverage=48994 exec total=125865 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:33:56 candidates=0 corpus=3256 coverage=48994 exec total=125877 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:34:06 candidates=0 corpus=3256 coverage=48994 exec total=125888 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:34:16 candidates=0 corpus=3256 coverage=48994 exec total=125900 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:34:26 candidates=0 corpus=3256 coverage=48994 exec total=125911 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:34:36 candidates=0 corpus=3256 coverage=48994 exec total=125923 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:34:46 candidates=0 corpus=3256 coverage=48994 exec total=125934 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:34:56 candidates=0 corpus=3256 coverage=48994 exec total=125946 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:35:06 candidates=0 corpus=3256 coverage=48994 exec total=125958 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:35:16 candidates=0 corpus=3256 coverage=48994 exec total=125969 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:35:26 candidates=0 corpus=3256 coverage=48994 exec total=125981 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:35:36 candidates=0 corpus=3256 coverage=48994 exec total=125992 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:35:46 candidates=0 corpus=3256 coverage=48994 exec total=126004 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:35:56 candidates=0 corpus=3256 coverage=48994 exec total=126015 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:36:06 candidates=0 corpus=3256 coverage=48994 exec total=126027 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:36:16 candidates=0 corpus=3256 coverage=48994 exec total=126039 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:36:26 candidates=0 corpus=3256 coverage=48994 exec total=126050 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:36:36 candidates=0 corpus=3256 coverage=48994 exec total=126062 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:36:46 candidates=0 corpus=3256 coverage=48994 exec total=126074 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:36:56 candidates=0 corpus=3256 coverage=48994 exec total=126085 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:37:06 candidates=0 corpus=3256 coverage=48994 exec total=126097 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:37:16 candidates=0 corpus=3256 coverage=48994 exec total=126109 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:37:26 candidates=0 corpus=3256 coverage=48994 exec total=126120 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:37:36 candidates=0 corpus=3256 coverage=48994 exec total=126132 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:37:46 candidates=0 corpus=3256 coverage=48994 exec total=126145 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:37:56 candidates=0 corpus=3256 coverage=48994 exec total=126160 (18/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:38:06 candidates=0 corpus=3256 coverage=48994 exec total=126174 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:38:16 candidates=0 corpus=3256 coverage=48994 exec total=126186 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:38:26 candidates=0 corpus=3256 coverage=48994 exec total=126197 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:38:36 candidates=0 corpus=3256 coverage=48994 exec total=126211 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:38:46 candidates=0 corpus=3256 coverage=48994 exec total=126226 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:38:56 candidates=0 corpus=3256 coverage=48994 exec total=126240 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:39:06 candidates=0 corpus=3256 coverage=48994 exec total=126253 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:39:16 candidates=0 corpus=3256 coverage=48994 exec total=126266 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:39:26 candidates=0 corpus=3256 coverage=48994 exec total=126280 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:39:36 candidates=0 corpus=3256 coverage=48994 exec total=126294 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:39:46 candidates=0 corpus=3256 coverage=48994 exec total=126308 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:39:56 candidates=0 corpus=3256 coverage=48994 exec total=126319 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:40:06 candidates=0 corpus=3256 coverage=48994 exec total=126331 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:40:16 candidates=0 corpus=3256 coverage=48994 exec total=126342 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:40:26 candidates=0 corpus=3256 coverage=48994 exec total=126354 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:40:36 candidates=0 corpus=3256 coverage=48994 exec total=126365 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:40:46 candidates=0 corpus=3256 coverage=48994 exec total=126377 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:40:56 candidates=0 corpus=3256 coverage=48994 exec total=126388 (17/sec) fuzzing VMs=1 reproducing=0 
2024/10/01 03:41:06 candidates=0 corpus=3256 coverage=48994 exec total=126400 (17/sec) fuzzing VMs=1 reproducing=0 
SIGINT: shutting down...
2024/10/01 03:41:16 vm-2: running for 59m38.297447897s, restarting
