mkdir in /home/clexma/Desktop/fox3/fuzzing
mkdir ./experiment_result/temp/0
cp -rf ./ChatAnalyzer/pathsFile.txt ./ChatAnalyzer/path_source_code.txt ./target_functions.txt ./ChatAnalyzer/syz_comm_content.txt ./ChatAnalyzer/syz_comm_sig.txt ./linuxRepo/line2addr/input_functions.txt ./linuxRepo/line2addr/func2addr_info.txt ./linuxRepo/line2addr/result_addr_info.txt  ./experiment_result/temp/0
cp ./target_functions.txt ./experiment_result/temp/0
cp ./syzkaller/experiment_output_llmenabled.txt ./experiment_result/temp/0
START EXP
----- target functions

kimage_is_destination_range

----- target functions

find_lock_entries

----- target functions

pmd_none_or_clear_bad

----- target functions

alloc_skb_with_frags
is llm enable: 1
close range: 2
0 CURRENT TARGET FUNCTIONS: 
kimage_is_destination_range
write target_functions.txt
b'close function: kimage_add_entry\nclose function: kimage_alloc_control_pages\nclose function: kimage_alloc_normal_control_pages\nclose function: kimage_alloc_page\nclose function: kimage_is_destination_range\nclose function: kimage_load_normal_segment\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 104 to: 214\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 318 to: 382\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 453 to: 470\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 472 to: 496\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 709 to: 777\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 249 to: 265\nLLM ENABLED\nCLOSE RANGE: 2\npython3 chat_interface.py init kimage_is_destination_range\ninit output: 1 syscall analysis for kimage_is_destination_range : ----------------------------\n[kexec_load, kexec_file_load]\nInit LLM result:\nkexec_load\nkexec_file_load\n\ninit error: \n/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer\npython3 chat_interface.py close kimage_is_destination_range 2\n/home/clexma/Desktop/fox3/fuzzing/linuxRepo/line2addr\npython3 ./addr_extractor.py ./input_functions.txt\nfuzzing terminate, time bound reach\n'
b'close function: kimage_add_entry\nclose function: kimage_alloc_control_pages\nclose function: kimage_alloc_normal_control_pages\nclose function: kimage_alloc_page\nclose function: kimage_is_destination_range\nclose function: kimage_load_normal_segment\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 104 to: 214\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 318 to: 382\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 453 to: 470\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 472 to: 496\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 709 to: 777\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/kernel/kexec_core.c\nline range: \nfrom: 249 to: 265\nLLM ENABLED\nCLOSE RANGE: 2\npython3 chat_interface.py init kimage_is_destination_range\ninit output: 1 syscall analysis for kimage_is_destination_range : ----------------------------\n[kexec_load, kexec_file_load]\nInit LLM result:\nkexec_load\nkexec_file_load\n\ninit error: \n/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer\npython3 chat_interface.py close kimage_is_destination_range 2\n/home/clexma/Desktop/fox3/fuzzing/linuxRepo/line2addr\npython3 ./addr_extractor.py ./input_functions.txt\nfuzzing terminate, time bound reach\n'
b'Traceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 128, in <module>\n    syzkaller_proc.wait(timeout=syzkaller_time_out)\n  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait\n    return self._wait(timeout=timeout)\n  File "/usr/lib/python3.10/subprocess.py", line 1951, in _wait\n    raise TimeoutExpired(self.args, timeout)\nsubprocess.TimeoutExpired: Command \'[\'sudo\', \'-s\', \'./bin/syz-manager\', \'-config\', \'./my.cfg\']\' timed out after 7200 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 132, in <module>\n    kill_process_tree(syzkaller_proc.pid)\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 14, in kill_process_tree\n    os.kill(child.pid, sig)\nPermissionError: [Errno 1] Operation not permitted\n'
python3 ./run_experiment.py copy 0
1 CURRENT TARGET FUNCTIONS: 
find_lock_entries
write target_functions.txt
b'close function: __jbd2_journal_erase\nclose function: filemap_invalidate_inode\nclose function: find_lock_entries\nclose function: generic_fadvise\nclose function: invalidate_mapping_pages\nclose function: mapping_try_invalidate\nclose function: shmem_fallocate\nclose function: shmem_truncate_range\nclose function: shmem_undo_range\nclose function: truncate_bdev_range\nclose function: truncate_inode_pages\nclose function: truncate_inode_pages_range\nclose function: truncate_pagecache_range\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/shmem.c\nline range: \nfrom: 964 to: 1110\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 546 to: 550\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/filemap.c\nline range: \nfrom: 2084 to: 2126\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/fadvise.c\nline range: \nfrom: 31 to: 177\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/fs/jbd2/journal.c\nline range: \nfrom: 1950 to: 2038\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/shmem.c\nline range: \nfrom: 1112 to: 1117\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 437 to: 440\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 320 to: 421\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 823 to: 845\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/filemap.c\nline range: \nfrom: 4191 to: 4229\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/block/bdev.c\nline range: \nfrom: 105 to: 132\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/shmem.c\nline range: \nfrom: 3080 to: 3232\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 488 to: 530\nLLM ENABLED\nCLOSE RANGE: 2\npython3 chat_interface.py init find_lock_entries\ninit output: 1 syscall analysis for find_lock_entries : ----------------------------\n```plaintext\n[write, fallocate, fadvise64]\n```\n\ninit error: Traceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 453, in <module>\n    assert(llm_list_result[0] == "[" and llm_list_result[-1] == "]")\nAssertionError\n\n/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer\npython3 chat_interface.py close find_lock_entries 2\n/home/clexma/Desktop/fox3/fuzzing/linuxRepo/line2addr\npython3 ./addr_extractor.py ./input_functions.txt\nfuzzing terminate, time bound reach\n'
mkdir in /home/clexma/Desktop/fox3/fuzzing
mkdir ./experiment_result/temp/1
cp -rf ./ChatAnalyzer/pathsFile.txt ./ChatAnalyzer/path_source_code.txt ./target_functions.txt ./ChatAnalyzer/syz_comm_content.txt ./ChatAnalyzer/syz_comm_sig.txt ./linuxRepo/line2addr/input_functions.txt ./linuxRepo/line2addr/func2addr_info.txt ./linuxRepo/line2addr/result_addr_info.txt  ./experiment_result/temp/1
cp ./target_functions.txt ./experiment_result/temp/1
cp ./syzkaller/experiment_output_llmenabled.txt ./experiment_result/temp/1
b'close function: __jbd2_journal_erase\nclose function: filemap_invalidate_inode\nclose function: find_lock_entries\nclose function: generic_fadvise\nclose function: invalidate_mapping_pages\nclose function: mapping_try_invalidate\nclose function: shmem_fallocate\nclose function: shmem_truncate_range\nclose function: shmem_undo_range\nclose function: truncate_bdev_range\nclose function: truncate_inode_pages\nclose function: truncate_inode_pages_range\nclose function: truncate_pagecache_range\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/shmem.c\nline range: \nfrom: 964 to: 1110\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 546 to: 550\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/filemap.c\nline range: \nfrom: 2084 to: 2126\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/fadvise.c\nline range: \nfrom: 31 to: 177\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/fs/jbd2/journal.c\nline range: \nfrom: 1950 to: 2038\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/shmem.c\nline range: \nfrom: 1112 to: 1117\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 437 to: 440\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 320 to: 421\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 823 to: 845\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/filemap.c\nline range: \nfrom: 4191 to: 4229\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/block/bdev.c\nline range: \nfrom: 105 to: 132\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/shmem.c\nline range: \nfrom: 3080 to: 3232\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/truncate.c\nline range: \nfrom: 488 to: 530\nLLM ENABLED\nCLOSE RANGE: 2\npython3 chat_interface.py init find_lock_entries\ninit output: 1 syscall analysis for find_lock_entries : ----------------------------\n```plaintext\n[write, fallocate, fadvise64]\n```\n\ninit error: Traceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer/chat_interface.py", line 453, in <module>\n    assert(llm_list_result[0] == "[" and llm_list_result[-1] == "]")\nAssertionError\n\n/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer\npython3 chat_interface.py close find_lock_entries 2\n/home/clexma/Desktop/fox3/fuzzing/linuxRepo/line2addr\npython3 ./addr_extractor.py ./input_functions.txt\nfuzzing terminate, time bound reach\n'
b'Traceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 128, in <module>\n    syzkaller_proc.wait(timeout=syzkaller_time_out)\n  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait\n    return self._wait(timeout=timeout)\n  File "/usr/lib/python3.10/subprocess.py", line 1951, in _wait\n    raise TimeoutExpired(self.args, timeout)\nsubprocess.TimeoutExpired: Command \'[\'sudo\', \'-s\', \'./bin/syz-manager\', \'-config\', \'./my.cfg\']\' timed out after 7200 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 132, in <module>\n    kill_process_tree(syzkaller_proc.pid)\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 14, in kill_process_tree\n    os.kill(child.pid, sig)\nPermissionError: [Errno 1] Operation not permitted\n'
python3 ./run_experiment.py copy 1
2 CURRENT TARGET FUNCTIONS: 
pmd_none_or_clear_bad
write target_functions.txt
b'close function: copy_pmd_range\nclose function: copy_pud_range\nclose function: free_pmd_range\nclose function: free_pud_range\nclose function: pmd_none_or_clear_bad\nclose function: vunmap_pmd_range\nclose function: vunmap_pud_range\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/memory.c\nline range: \nfrom: 1211 to: 1245\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/vmalloc.c\nline range: \nfrom: 387 to: 408\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/memory.c\nline range: \nfrom: 1248 to: 1282\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/memory.c\nline range: \nfrom: 232 to: 264\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/memory.c\nline range: \nfrom: 198 to: 230\ncurrent function name file path: NOT FOUND\nNOT FOUND\nline range: \nfrom: -1 to: -1\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/vmalloc.c\nline range: \nfrom: 362 to: 385\nLLM ENABLED\nCLOSE RANGE: 2\npython3 chat_interface.py init pmd_none_or_clear_bad\ninit output: 1 syscall analysis for pmd_none_or_clear_bad : ----------------------------\n[brk, munmap, mremap, mmap, mmap2, madvise, mprotect, msync]\nInit LLM result:\nbrk\nmunmap\nmremap\nmmap\nmmap2\nmadvise\nmprotect\nmsync\n\ninit error: \n/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer\npython3 chat_interface.py close pmd_none_or_clear_bad 2\n/home/clexma/Desktop/fox3/fuzzing/linuxRepo/line2addr\npython3 ./addr_extractor.py ./input_functions.txt\nfuzzing terminate, time bound reach\n'
b'close function: copy_pmd_range\nclose function: copy_pud_range\nclose function: free_pmd_range\nclose function: free_pud_range\nclose function: pmd_none_or_clear_bad\nclose function: vunmap_pmd_range\nclose function: vunmap_pud_range\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/memory.c\nline range: \nfrom: 1211 to: 1245\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/vmalloc.c\nline range: \nfrom: 387 to: 408\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/memory.c\nline range: \nfrom: 1248 to: 1282\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/memory.c\nline range: \nfrom: 232 to: 264\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/memory.c\nline range: \nfrom: 198 to: 230\ncurrent function name file path: NOT FOUND\nNOT FOUND\nline range: \nfrom: -1 to: -1\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/mm/vmalloc.c\nline range: \nfrom: 362 to: 385\nLLM ENABLED\nCLOSE RANGE: 2\npython3 chat_interface.py init pmd_none_or_clear_bad\ninit output: 1 syscall analysis for pmd_none_or_clear_bad : ----------------------------\n[brk, munmap, mremap, mmap, mmap2, madvise, mprotect, msync]\nInit LLM result:\nbrk\nmunmap\nmremap\nmmap\nmmap2\nmadvise\nmprotect\nmsync\n\ninit error: \n/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer\npython3 chat_interface.py close pmd_none_or_clear_bad 2\n/home/clexma/Desktop/fox3/fuzzing/linuxRepo/line2addr\npython3 ./addr_extractor.py ./input_functions.txt\nfuzzing terminate, time bound reach\n'
mkdir in /home/clexma/Desktop/fox3/fuzzing
mkdir ./experiment_result/temp/2
cp -rf ./ChatAnalyzer/pathsFile.txt ./ChatAnalyzer/path_source_code.txt ./target_functions.txt ./ChatAnalyzer/syz_comm_content.txt ./ChatAnalyzer/syz_comm_sig.txt ./linuxRepo/line2addr/input_functions.txt ./linuxRepo/line2addr/func2addr_info.txt ./linuxRepo/line2addr/result_addr_info.txt  ./experiment_result/temp/2
cp ./target_functions.txt ./experiment_result/temp/2
cp ./syzkaller/experiment_output_llmenabled.txt ./experiment_result/temp/2
mkdir in /home/clexma/Desktop/fox3/fuzzing
mkdir ./experiment_result/temp/3
cp -rf ./ChatAnalyzer/pathsFile.txt ./ChatAnalyzer/path_source_code.txt ./target_functions.txt ./ChatAnalyzer/syz_comm_content.txt ./ChatAnalyzer/syz_comm_sig.txt ./linuxRepo/line2addr/input_functions.txt ./linuxRepo/line2addr/func2addr_info.txt ./linuxRepo/line2addr/result_addr_info.txt  ./experiment_result/temp/3
cp ./target_functions.txt ./experiment_result/temp/3
cp ./syzkaller/experiment_output_llmenabled.txt ./experiment_result/temp/3
b'usage: line2addr.py [-h] --binary BINARY [--json-db] [--file FILE]\n                    [--line LINE] [--directory DIRECTORY]\n                    [--base-address BASE_ADDRESS] [--dwarf]\nline2addr.py: error: unrecognized arguments: FOUND\nTraceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 128, in <module>\n    syzkaller_proc.wait(timeout=syzkaller_time_out)\n  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait\n    return self._wait(timeout=timeout)\n  File "/usr/lib/python3.10/subprocess.py", line 1951, in _wait\n    raise TimeoutExpired(self.args, timeout)\nsubprocess.TimeoutExpired: Command \'[\'sudo\', \'-s\', \'./bin/syz-manager\', \'-config\', \'./my.cfg\']\' timed out after 7200 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 132, in <module>\n    kill_process_tree(syzkaller_proc.pid)\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 14, in kill_process_tree\n    os.kill(child.pid, sig)\nPermissionError: [Errno 1] Operation not permitted\n'
python3 ./run_experiment.py copy 2
3 CURRENT TARGET FUNCTIONS: 
alloc_skb_with_frags
write target_functions.txt
b'close function: alloc_skb_with_frags\nclose function: packet_alloc_skb\nclose function: sock_alloc_send_pskb\nclose function: sock_alloc_send_skb\nclose function: tcp_send_rcvq\nclose function: tcp_sendmsg_locked\nclose function: unix_dgram_sendmsg\nclose function: unix_stream_sendmsg\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/unix/af_unix.c\nline range: \nfrom: 2188 to: 2319\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/ipv4/tcp_input.c\nline range: \nfrom: 5089 to: 5139\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/core/sock.c\nline range: \nfrom: 2764 to: 2805\ncurrent function name file path: NOT FOUND\nNOT FOUND\nline range: \nfrom: -1 to: -1\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/packet/af_packet.c\nline range: \nfrom: 2916 to: 2940\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/core/skbuff.c\nline range: \nfrom: 6488 to: 6540\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/unix/af_unix.c\nline range: \nfrom: 1910 to: 2128\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/ipv4/tcp.c\nline range: \nfrom: 1045 to: 1340\nLLM ENABLED\nCLOSE RANGE: 2\npython3 chat_interface.py init alloc_skb_with_frags\ninit output: 1 syscall analysis for alloc_skb_with_frags : ----------------------------\n[sendmsg, sendto]\nInit LLM result:\nsendmsg\nsendto\n\ninit error: \n/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer\npython3 chat_interface.py close alloc_skb_with_frags 2\n/home/clexma/Desktop/fox3/fuzzing/linuxRepo/line2addr\npython3 ./addr_extractor.py ./input_functions.txt\nfuzzing terminate, time bound reach\n'
b'close function: alloc_skb_with_frags\nclose function: packet_alloc_skb\nclose function: sock_alloc_send_pskb\nclose function: sock_alloc_send_skb\nclose function: tcp_send_rcvq\nclose function: tcp_sendmsg_locked\nclose function: unix_dgram_sendmsg\nclose function: unix_stream_sendmsg\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/unix/af_unix.c\nline range: \nfrom: 2188 to: 2319\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/ipv4/tcp_input.c\nline range: \nfrom: 5089 to: 5139\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/core/sock.c\nline range: \nfrom: 2764 to: 2805\ncurrent function name file path: NOT FOUND\nNOT FOUND\nline range: \nfrom: -1 to: -1\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/packet/af_packet.c\nline range: \nfrom: 2916 to: 2940\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/core/skbuff.c\nline range: \nfrom: 6488 to: 6540\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/unix/af_unix.c\nline range: \nfrom: 1910 to: 2128\ncurrent function name file path: /home/clexma/Desktop/fox3/fuzzing/linuxRepo//linux_new/net/ipv4/tcp.c\nline range: \nfrom: 1045 to: 1340\nLLM ENABLED\nCLOSE RANGE: 2\npython3 chat_interface.py init alloc_skb_with_frags\ninit output: 1 syscall analysis for alloc_skb_with_frags : ----------------------------\n[sendmsg, sendto]\nInit LLM result:\nsendmsg\nsendto\n\ninit error: \n/home/clexma/Desktop/fox3/fuzzing/ChatAnalyzer\npython3 chat_interface.py close alloc_skb_with_frags 2\n/home/clexma/Desktop/fox3/fuzzing/linuxRepo/line2addr\npython3 ./addr_extractor.py ./input_functions.txt\nfuzzing terminate, time bound reach\n'
b'usage: line2addr.py [-h] --binary BINARY [--json-db] [--file FILE]\n                    [--line LINE] [--directory DIRECTORY]\n                    [--base-address BASE_ADDRESS] [--dwarf]\nline2addr.py: error: unrecognized arguments: FOUND\nTraceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 128, in <module>\n    syzkaller_proc.wait(timeout=syzkaller_time_out)\n  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait\n    return self._wait(timeout=timeout)\n  File "/usr/lib/python3.10/subprocess.py", line 1951, in _wait\n    raise TimeoutExpired(self.args, timeout)\nsubprocess.TimeoutExpired: Command \'[\'sudo\', \'-s\', \'./bin/syz-manager\', \'-config\', \'./my.cfg\']\' timed out after 7200 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 132, in <module>\n    kill_process_tree(syzkaller_proc.pid)\n  File "/home/clexma/Desktop/fox3/fuzzing/./run_experiment.py", line 14, in kill_process_tree\n    os.kill(child.pid, sig)\nPermissionError: [Errno 1] Operation not permitted\n'
python3 ./run_experiment.py copy 3
